name: Deploy
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine keyring keyrings.google-artifactregistry-auth
    - name: Build
      run: |
        python setup.py sdist bdist_wheel
    - id: auth
      uses: google-github-actions/auth@v1.1.1
      with:
        workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ vars.SERVICE_ACCOUNT }}
    - name: Upload to Artifact Registry
      run: |
        gcloud config set account ${{ vars.SERVICE_ACCOUNT }}
        gcloud artifacts print-settings python \
          --project=${{ vars.REPOSITORY_PROJECT }} \
          --repository=${{ vars.REPOSITORY }} \
          --location=${{ vars.REPOSITORY_LOCATION }} > ~/.pypirc
        python -m twine upload --repository-url ${{ vars.REPOSITORY_URL }} dist/*
